services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    command: python3 manage.py runserver 0.0.0.0:8000

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - db

    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "15432:5432"

volumes:
  pgdata:
