# Generated by Django 5.2.5 on 2025-08-23 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_fileuploadjob'),
        ('catalog', '0010_album_artists_alter_albumartist_album_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StreamingHistory',
            new_name='ListeningHistory',
        ),
    ]
