# Generated by Django 5.2.5 on 2025-08-26 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_streaminghistory_listeninghistory'),
        ('catalog', '0016_album_spotify_id_artist_spotify_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listeninghistory',
            constraint=models.UniqueConstraint(fields=('user', 'played_at'), name='unique_user_played_at'),
        ),
    ]
