# Generated by Django 5.2.5 on 2025-08-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_track_album_alter_track_artist'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('spotify_track_uri', 'artist', 'album'), name='unique_artist_album_spotify_track_uri'),
        ),
    ]
