# Generated by Django 5.2.5 on 2025-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_album_artist_albumartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='primary_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='primary_albums', to='catalog.artist'),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artists', to='catalog.album'),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_albums', to='catalog.artist'),
        ),
    ]
