# Generated by Django 5.2.5 on 2025-08-18 20:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_album_primary_artist_alter_albumartist_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_artist_album_spotify_track_uri',
        ),
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='trackartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.artist'),
        ),
        migrations.AddField(
            model_name='trackartist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='tracks', through='catalog.TrackArtist', to='catalog.artist'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('spotify_track_uri', 'album'), name='unique_album_spotify_track_uri'),
        ),
        migrations.AddConstraint(
            model_name='trackartist',
            constraint=models.UniqueConstraint(fields=('track', 'artist'), name='unique_track_artist'),
        ),
    ]
