# Generated by Django 5.2.5 on 2025-08-18 21:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_trackartist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='track',
            name='unique_album_spotify_track_uri',
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='trackalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.album'),
        ),
        migrations.AddField(
            model_name='trackalbum',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(related_name='tracks', through='catalog.TrackAlbum', to='catalog.album'),
        ),
        migrations.AddConstraint(
            model_name='trackalbum',
            constraint=models.UniqueConstraint(fields=('track', 'album'), name='unique_track_album'),
        ),
    ]
