# Generated by Django 5.2.5 on 2025-08-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_trackalbum_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='spotify_track_uri',
            new_name='spotify_uri',
        ),
    ]
