# Generated by Django 5.2.5 on 2025-08-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_spotify_track_uri_track_spotify_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='primary_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='primary_albums', to='catalog.artist'),
        ),
    ]
