# Generated by Django 5.2.5 on 2025-08-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_album_artists_alter_albumartist_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='spotify_uri',
        ),
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default='', max_length=62, unique=True),
            preserve_default=False,
        ),
    ]
