# Generated by Django 5.2.5 on 2025-08-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_track_spotify_uri_track_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='albums',
        ),
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.album'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TrackAlbum',
        ),
    ]
