# Generated by Django 5.2.5 on 2025-08-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_track_albums_track_album_delete_trackalbum'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='album',
            name='unique_album_name_primary_artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='primary_artist',
        ),
    ]
