# Generated by Django 5.2.5 on 2025-08-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='cover_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
