# Generated by Django 5.2.5 on 2025-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_album_cover_url_artist_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spotify_id',
            field=models.CharField(default='', max_length=62, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default='', max_length=62, unique=True),
            preserve_default=False,
        ),
    ]
